/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xiruqxqkamxtxwvmqagk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpcnVxeHFrYW14dHh3dm1xYWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MzkxNjcsImV4cCI6MjA3ODExNTE2N30.xZ1D2ycq4EyusUafP4-1qm0P9-hLUhfh3zGUOGMgIvU"